<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create the reset_password_request table (initial stub: id only).
 *
 * The remaining columns are added in a later migration because this one had
 * already been executed before the entity was completed.
 */
final class Version20260622021100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create reset_password_request table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE reset_password_request');
    }
}
